// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYW0TePBqvPbj3bQoPc_8M-m7TeSnDgEY',
    appId: '1:736756584053:web:d887b0da05b34fdef4f23c',
    messagingSenderId: '736756584053',
    projectId: 'mental-manager-3a2f8',
    authDomain: 'mental-manager-3a2f8.firebaseapp.com',
    storageBucket: 'mental-manager-3a2f8.appspot.com',
    measurementId: 'G-B1R8BNXBZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaYBY1UTSE0BsVMNRfn4AUYj_FzKwBXLQ',
    appId: '1:736756584053:android:a45cbd0f2b00b58df4f23c',
    messagingSenderId: '736756584053',
    projectId: 'mental-manager-3a2f8',
    storageBucket: 'mental-manager-3a2f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzePe1KEQ-mFBa2Pu1Pk97r-QQDGvJpeo',
    appId: '1:736756584053:ios:5543ab93e8c4c156f4f23c',
    messagingSenderId: '736756584053',
    projectId: 'mental-manager-3a2f8',
    storageBucket: 'mental-manager-3a2f8.appspot.com',
    iosClientId: '736756584053-qho8m4iianamfjiifog3tu0e325su3c7.apps.googleusercontent.com',
    iosBundleId: 'com.tera1994.mentalManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzePe1KEQ-mFBa2Pu1Pk97r-QQDGvJpeo',
    appId: '1:736756584053:ios:9b1a7483b0c25d63f4f23c',
    messagingSenderId: '736756584053',
    projectId: 'mental-manager-3a2f8',
    storageBucket: 'mental-manager-3a2f8.appspot.com',
    iosClientId: '736756584053-1jlvbqoa2erttslk2a8er97qik05vj4k.apps.googleusercontent.com',
    iosBundleId: 'com.tera1994.mentalManager.RunnerTests',
  );
}
